import { TERRAIN_MAPS } from './terrain-maps.js';
import { PHASE3_MAPS, PHASE3_ENEMIES, PHASE3_WEAPONS } from './expansion.js';
// Phase II content extends the original field kit without changing its stable IDs.
export const EXTRA_WEAPONS = [
  {
    id: 'spire',
    name: 'SPIRE / 22',
    class: 'Submachine gun',
    tag: 'RAPID FIRE',
    role: 'Fast movement and a generous magazine. Poor armor performance; stay close.',
    damage: 15,
    rate: 15,
    mag: 40,
    reserve: 240,
    reload: 1.35,
    spread: 0.025,
    recoil: 0.013,
    range: 42,
    penetration: 0.12,
    weak: 2,
    auto: true,
    color: 0x84aba5,
    length: 0.65,
    pitch: 190,
    cost: 150,
    mobility: 1.12,
    category: 'primary',
  },
  {
    id: 'triptych',
    name: 'TRIPTYCH / 3',
    class: 'Burst rifle',
    tag: 'THREE-ROUND BURST',
    role: 'Three tightly spaced shots per trigger pull. Burst delay punishes missed volleys.',
    damage: 27,
    rate: 12,
    mag: 27,
    reserve: 189,
    reload: 1.8,
    spread: 0.008,
    recoil: 0.012,
    range: 95,
    penetration: 0.4,
    weak: 2.1,
    burst: 3,
    burstDelay: 0.34,
    color: 0xb8a582,
    length: 1,
    pitch: 130,
    cost: 180,
    category: 'primary',
  },
  {
    id: 'ballast',
    name: 'BALLAST / 60',
    class: 'Light machine gun',
    tag: 'SUPPRESSION',
    role: 'Long sustained fire staggers light machines. Heavy handling and a slow reload.',
    damage: 22,
    rate: 11,
    mag: 60,
    reserve: 240,
    reload: 3.2,
    spread: 0.022,
    recoil: 0.024,
    range: 85,
    penetration: 0.38,
    weak: 1.8,
    auto: true,
    stagger: 0.12,
    mobility: 0.83,
    color: 0x9a986a,
    length: 1.2,
    pitch: 80,
    cost: 260,
    category: 'primary',
  },
  {
    id: 'kiln',
    name: 'KILN / 45',
    class: 'Battle rifle',
    tag: 'HEAVY KINETIC',
    role: 'Deliberate semi-automatic fire breaks armor. Strong recoil requires controlled shots.',
    damage: 53,
    rate: 3.5,
    mag: 14,
    reserve: 112,
    reload: 2,
    spread: 0.005,
    recoil: 0.034,
    range: 110,
    penetration: 0.65,
    weak: 2.2,
    color: 0xb99b85,
    length: 1.05,
    pitch: 100,
    cost: 210,
    category: 'primary',
  },
  {
    id: 'arc',
    name: 'ARC / ION',
    class: 'Energy carbine',
    tag: 'HEAT / RECHARGE',
    role: 'Ammunition-free pulse fire. Heat builds quickly; vent with R or let the coils cool.',
    damage: 26,
    rate: 7,
    mag: 100,
    reserve: 0,
    reload: 1.6,
    spread: 0.009,
    recoil: 0.011,
    range: 85,
    penetration: 0.6,
    weak: 1.9,
    auto: true,
    energy: true,
    heatPerShot: 17,
    color: 0x7fd7d8,
    length: 0.95,
    pitch: 480,
    cost: 300,
    category: 'primary',
  },
  {
    id: 'anvil',
    name: 'ANVIL / 50',
    class: 'Heavy pistol',
    tag: 'ARMOR BREAKER',
    role: 'Seven powerful rounds. Strong penetration, small magazine, and deliberate handling.',
    damage: 62,
    rate: 2.4,
    mag: 7,
    reserve: 56,
    reload: 1.6,
    spread: 0.008,
    recoil: 0.05,
    range: 65,
    penetration: 0.7,
    weak: 2.3,
    color: 0xbab5a2,
    length: 0.6,
    pitch: 95,
    cost: 140,
    category: 'secondary',
  },
  {
    id: 'stitch',
    name: 'STITCH / 18',
    class: 'Machine pistol',
    tag: 'AUTOMATIC SIDEARM',
    role: 'A compact panic button for nearby rushers. Low penetration and rapid ammunition use.',
    damage: 13,
    rate: 13,
    mag: 24,
    reserve: 144,
    reload: 1.25,
    spread: 0.03,
    recoil: 0.016,
    range: 30,
    penetration: 0.1,
    weak: 2,
    auto: true,
    mobility: 1.08,
    color: 0x999fb1,
    length: 0.5,
    pitch: 230,
    cost: 140,
    category: 'secondary',
  },
  {
    id: 'glint',
    name: 'GLINT / CELL',
    class: 'Energy sidearm',
    tag: 'HEAT / PRECISION',
    role: 'Accurate energy pulses recharge without ammunition. Overheating forces a pause.',
    damage: 40,
    rate: 3,
    mag: 100,
    reserve: 0,
    reload: 1.5,
    spread: 0.004,
    recoil: 0.017,
    range: 70,
    penetration: 0.45,
    weak: 2.4,
    energy: true,
    heatPerShot: 25,
    color: 0x81c1df,
    length: 0.5,
    pitch: 700,
    cost: 200,
    category: 'secondary',
  },
  {
    id: 'mortar',
    name: 'FRACTURE / 4',
    class: 'Grenade launcher',
    tag: 'BALLISTIC / AREA',
    role: 'Lob arcing grenades over low cover. Broad blasts reward predicting movement.',
    damage: 125,
    rate: 1.5,
    mag: 4,
    reserve: 20,
    reload: 2.7,
    spread: 0.01,
    recoil: 0.045,
    range: 75,
    penetration: 0.65,
    weak: 1,
    explosive: 5.5,
    gravity: 13,
    speed: 22,
    fuse: 3,
    color: 0xa3a86c,
    length: 0.85,
    pitch: 55,
    cost: 240,
    category: 'heavy',
  },
  {
    id: 'lance',
    name: 'LANCE / ZERO',
    class: 'Rail driver',
    tag: 'CHARGED / PENETRATING',
    role: 'Hold fire to charge a penetrating shot through up to three machines. Limited ammunition.',
    damage: 190,
    rate: 1,
    mag: 3,
    reserve: 15,
    reload: 2.7,
    spread: 0.001,
    recoil: 0.075,
    range: 150,
    penetration: 1,
    weak: 2.5,
    charge: 0.75,
    pierce: 3,
    color: 0x94dddb,
    length: 1.4,
    pitch: 70,
    cost: 350,
    category: 'heavy',
  },
];

export const EXTRA_ENEMIES = {
  bulwark: {
    name: 'BULWARK',
    hp: 170,
    armor: 90,
    speed: 2,
    radius: 0.8,
    height: 2.7,
    cost: 3,
    reward: 65,
    color: 0x687e96,
    attack: 'rifle',
    damage: 12,
    interval: 2,
    shield: 210,
  },
  mender: {
    name: 'MENDER',
    hp: 105,
    armor: 25,
    speed: 3.1,
    radius: 0.65,
    height: 2.2,
    cost: 3,
    reward: 65,
    color: 0x659e8b,
    attack: 'support',
    damage: 7,
    interval: 2.8,
  },
  lancer: {
    name: 'LANCER',
    hp: 95,
    armor: 30,
    speed: 3.5,
    radius: 0.6,
    height: 2.8,
    cost: 3,
    reward: 60,
    color: 0x9289ac,
    attack: 'sniper',
    damage: 28,
    interval: 3.8,
  },
  volatile: {
    name: 'VOLATILE',
    hp: 50,
    armor: 0,
    speed: 6.6,
    radius: 0.6,
    height: 1.05,
    cost: 2,
    reward: 35,
    color: 0xc17a45,
    attack: 'suicide',
    damage: 35,
    interval: 1,
  },
  conductor: {
    name: 'THE CONDUCTOR',
    hp: 1650,
    armor: 420,
    speed: 1.5,
    radius: 1.65,
    height: 5.8,
    cost: 20,
    reward: 600,
    color: 0x7f817c,
    attack: 'boss',
    damage: 24,
    interval: 3.8,
    boss: true,
  },
};

export const MAPS = [
  {
    id: 'ashworks',
    name: 'ASHWORKS',
    region: 'THE INDUSTRIAL BELT',
    tag: 'COVER / ELEVATION',
    description:
      'Fight through furnace lanes and a raised service deck. Break line of sight around the extraction tower.',
    accent: '#f5a16e',
    sky: 0x18292c,
    fog: 0x233235,
    sun: 0xffdeb2,
    start: [0, 0, 20],
  },
  {
    id: 'sunbreak',
    name: 'SUNBREAK RELAY',
    region: 'THE GLASS DESERT',
    tag: 'LONG SIGHTLINES / FLANKS',
    description:
      'A shattered signal dish overlooks open dunes, split relay bunkers and a stepped observation platform.',
    accent: '#e3bf79',
    sky: 0xaca18a,
    fog: 0xb8aa8b,
    sun: 0xffe6ba,
    start: [0, 0, 26],
  },
  {
    id: 'whiteout',
    name: 'WHITEOUT ARRAY',
    region: 'THE POLAR ARCHIVE',
    tag: 'CHOKEPOINTS / COURTYARDS',
    description:
      'Laboratory corridors connect two snowbound courtyards. Close doors of sight and control the crossings.',
    accent: '#95cdda',
    sky: 0x708d9c,
    fog: 0x87a5b4,
    sun: 0xd2e9ff,
    start: [0, 0, 27],
  },
];
export const DIFFICULTIES = {
  recruit: {
    name: 'RECRUIT',
    description: 'Slower reactions, fewer reinforcements, generous recovery.',
    budget: 0.75,
    aggression: 0.8,
    accuracy: 1.7,
    damage: 0.75,
    elite: 0,
    recovery: 50,
    ammo: 1,
    reward: 0.85,
  },
  operative: {
    name: 'OPERATIVE',
    description: 'The intended encounter. Mixed formations and limited recovery.',
    budget: 1,
    aggression: 1,
    accuracy: 1,
    damage: 1,
    elite: 0.08,
    recovery: 35,
    ammo: 1,
    reward: 1,
  },
  veteran: {
    name: 'VETERAN',
    description: 'More flanking machines, faster reactions and elite escorts.',
    budget: 1.3,
    aggression: 1.2,
    accuracy: 0.7,
    damage: 1.1,
    elite: 0.2,
    recovery: 25,
    ammo: 0.8,
    reward: 1.25,
  },
  nightmare: {
    name: 'NIGHTMARE',
    description: 'Relentless formations, accurate fire and scarce resupplies.',
    budget: 1.6,
    aggression: 1.4,
    accuracy: 0.45,
    damage: 1.2,
    elite: 0.32,
    recovery: 15,
    ammo: 0.65,
    reward: 1.5,
  },
};
export const LOADOUT_SLOTS = [
  { name: 'PRIMARY', category: 'primary' },
  { name: 'ALTERNATE', category: 'primary' },
  { name: 'RESERVE PRIMARY', category: 'primary' },
  { name: 'HEAVY', category: 'heavy' },
  { name: 'SIDEARM', category: 'secondary' },
];
export const EQUIPMENT = {
  repair: {
    name: 'FIELD PATCH',
    description: 'Q: Restore 35 health and 15 armor. Two charges per wave.',
    charges: 2,
  },
  emp: {
    name: 'NULL PULSE',
    description: 'Q: Stun machines and shatter shields within 10m. Two charges per wave.',
    charges: 2,
  },
  grenade: {
    name: 'SHARD GRENADE',
    description: 'Q: Throw an arcing explosive. Three charges per wave.',
    charges: 3,
  },
};
export const MELEE = {
  blade: { name: 'SHOCK BLADE', damage: 75, cooldown: 0.7, stagger: 0.4, range: 3.1 },
  hammer: { name: 'BREAKER HAMMER', damage: 145, cooldown: 1.45, stagger: 0.9, range: 2.8 },
};

MAPS.push(...PHASE3_MAPS, ...TERRAIN_MAPS);
Object.assign(EXTRA_ENEMIES, PHASE3_ENEMIES);
EXTRA_WEAPONS.push(...PHASE3_WEAPONS);
