import { EXTRA_WEAPONS, EXTRA_ENEMIES } from './content.js';
import { FACTION_ENEMIES } from './factions.js';
export const WEAPONS = [
  {
    id: 'rivet',
    name: 'RIVET / 31',
    class: 'Assault rifle',
    tag: 'KINETIC',
    role: 'Reliable automatic fire. Strip plating, then finish the exposed sensor.',
    damage: 23,
    rate: 9,
    mag: 30,
    reserve: 210,
    reload: 1.7,
    spread: 0.008,
    recoil: 0.018,
    range: 90,
    penetration: 0.3,
    weak: 2.3,
    pellets: 1,
    auto: true,
    color: 0xe3b06e,
    length: 1,
    pitch: 115,
  },
  {
    id: 'breach',
    name: 'BREACH / 8',
    class: 'Scattergun',
    tag: 'HIGH STAGGER',
    role: 'Eight-pellet close-range punch. Stops charging machines in their tracks.',
    damage: 14,
    rate: 1.25,
    mag: 7,
    reserve: 49,
    reload: 2.2,
    spread: 0.075,
    recoil: 0.06,
    range: 35,
    penetration: 0.15,
    weak: 1.7,
    pellets: 8,
    auto: false,
    color: 0xc88357,
    length: 0.85,
    pitch: 60,
  },
  {
    id: 'needle',
    name: 'NEEDLE / 06',
    class: 'Precision rifle',
    tag: 'ARMOR PIERCING',
    role: 'Slow, deliberate sensor shots. Pierces heavy plating with minimal damage loss.',
    damage: 90,
    rate: 1.5,
    mag: 6,
    reserve: 48,
    reload: 2.1,
    spread: 0.002,
    recoil: 0.04,
    range: 130,
    penetration: 0.85,
    weak: 2.8,
    pellets: 1,
    auto: false,
    color: 0x91c9c1,
    length: 1.3,
    pitch: 90,
  },
  {
    id: 'cinder',
    name: 'CINDER / R',
    class: 'Rocket launcher',
    tag: 'EXPLOSIVE',
    role: 'Traveling rockets punish clusters. Keep your distance from the blast.',
    damage: 170,
    rate: 0.8,
    mag: 1,
    reserve: 8,
    reload: 2.5,
    spread: 0.006,
    recoil: 0.07,
    range: 120,
    penetration: 0.8,
    weak: 1,
    pellets: 1,
    auto: false,
    explosive: 6,
    color: 0xe89757,
    length: 1.2,
    pitch: 45,
  },
  {
    id: 'relay',
    name: 'RELAY / 9',
    class: 'Sidearm',
    tag: 'EMERGENCY RESERVE',
    role: 'Accurate backup with regenerating reserve ammunition. Never stranded.',
    damage: 30,
    rate: 4,
    mag: 12,
    reserve: 72,
    reload: 1.15,
    spread: 0.009,
    recoil: 0.022,
    range: 65,
    penetration: 0.2,
    weak: 2.4,
    pellets: 1,
    auto: false,
    color: 0xb8c5c4,
    length: 0.55,
    pitch: 170,
  },
];
export const ENEMIES = {
  skitter: {
    name: 'SKITTER',
    hp: 60,
    armor: 0,
    speed: 6,
    radius: 0.6,
    height: 1.05,
    cost: 1,
    reward: 20,
    color: 0x776d58,
    attack: 'melee',
    damage: 12,
    interval: 1.1,
  },
  warden: {
    name: 'WARDEN',
    hp: 115,
    armor: 65,
    speed: 2.7,
    radius: 0.65,
    height: 2.5,
    cost: 2,
    reward: 40,
    color: 0x6b7776,
    attack: 'rifle',
    damage: 10,
    interval: 1.65,
  },
  bastion: {
    name: 'BASTION',
    hp: 310,
    armor: 200,
    speed: 1.6,
    radius: 1.15,
    height: 3.7,
    cost: 5,
    reward: 100,
    color: 0x91816a,
    attack: 'cannon',
    damage: 23,
    interval: 3.5,
  },
};
export { WAVE_RULES as WAVES } from './director.js';
export const DEFAULT_SETTINGS = {
  volume: 0.55,
  sensitivity: 1,
  fov: 80,
  quality: 'high',
  shake: 0.5,
};
export const CONTROLS = [
  ['W A S D', 'Move'],
  ['MOUSE', 'Look / aim'],
  ['LMB / RMB', 'Fire / aim down sights'],
  ['SHIFT', 'Sprint'],
  ['CTRL / C', 'Crouch / slide while sprinting'],
  ['SPACE', 'Jump / wall jump / W + mantle'],
  ['R', 'Reload / vent'],
  ['1 – 5 / WHEEL', 'Switch weapon'],
  ['V / F', 'Equipped melee tool'],
  ['E', 'Use resupply / begin wave'],
  ['ESC', 'Pause'],
];

WEAPONS.forEach((w, n) =>
  Object.assign(w, {
    category: n === 3 ? 'heavy' : n === 4 ? 'secondary' : 'primary',
    cost: 0,
    mobility: 1,
  }),
);
WEAPONS.push(...EXTRA_WEAPONS.map((w) => ({ pellets: 1, auto: false, mobility: 1, ...w })));
Object.assign(ENEMIES, EXTRA_ENEMIES);
Object.values(ENEMIES).forEach((d) => {
  d.faction = 'choir';
});
Object.assign(ENEMIES, FACTION_ENEMIES);
DEFAULT_SETTINGS.music = 0.3;
DEFAULT_SETTINGS.effects = 0.8;
DEFAULT_SETTINGS.particles = true;
DEFAULT_SETTINGS.shadows = true;
CONTROLS.splice(CONTROLS.length - 1, 0, ['Q', 'Use equipment']);

CONTROLS.splice(CONTROLS.length - 1, 0, ['B', 'Between-wave upgrades']);
