export const PHASE3_MAPS = [
  {
    id: 'cinderline',
    name: 'CINDERLINE',
    region: 'THE ABANDONED MEGACITY',
    tag: 'STREETS / CROSSFIRES',
    description:
      'Ruined city blocks divide an open avenue. Cross elevated transit steps and fight through service alleys.',
    accent: '#c5acdc',
    sky: 0x343143,
    fog: 0x494452,
    sun: 0xead4c1,
    start: [0, 0, 27],
    boss: 'architect',
  },
  {
    id: 'deepwell',
    name: 'DEEPWELL',
    region: 'THE MACHINE COMPLEX',
    tag: 'CHAMBERS / LIVE HAZARDS',
    description:
      'Descend into the Choir’s fabrication grid. Timed discharge fields punish static positions; quench them at the cache.',
    accent: '#88d6b6',
    sky: 0x0b2020,
    fog: 0x163938,
    sun: 0xa9e4d5,
    start: [0, 0, 27],
    boss: 'architect',
  },
];
export const PHASE3_ENEMIES = {
  fabricator: {
    name: 'FABRICATOR',
    hp: 220,
    armor: 110,
    speed: 1.9,
    radius: 0.9,
    height: 3.3,
    cost: 5,
    reward: 110,
    color: 0x86956d,
    attack: 'rifle',
    damage: 9,
    interval: 2.7,
  },
  cantor: {
    name: 'CANTOR',
    hp: 150,
    armor: 55,
    speed: 2.5,
    radius: 0.7,
    height: 3,
    cost: 4,
    reward: 90,
    color: 0xb9aa78,
    attack: 'rifle',
    damage: 10,
    interval: 2.3,
  },
  shade: {
    name: 'SHADE',
    hp: 90,
    armor: 25,
    speed: 4.3,
    radius: 0.6,
    height: 2.4,
    cost: 3,
    reward: 70,
    color: 0x69858d,
    attack: 'rifle',
    damage: 12,
    interval: 2,
  },
  architect: {
    name: 'THE ARCHITECT',
    hp: 1500,
    armor: 340,
    speed: 1.1,
    radius: 1.7,
    height: 4.8,
    cost: 22,
    reward: 700,
    color: 0x7a9290,
    attack: 'boss',
    damage: 22,
    interval: 3.6,
    boss: true,
  },
};

export const PHASE3_WEAPONS = [
  {
    id: 'rime',
    name: 'RIME / CRYO',
    class: 'Cryogenic carbine',
    tag: 'ENERGY / SLOW',
    role: 'Coolant pulses slow machines for two seconds. Lower damage trades lethality for control.',
    damage: 18,
    rate: 8,
    mag: 100,
    reserve: 0,
    reload: 1.7,
    spread: 0.012,
    recoil: 0.009,
    range: 70,
    penetration: 0.35,
    weak: 2,
    auto: true,
    energy: true,
    heatPerShot: 13,
    slow: 2,
    color: 0x97d9e9,
    length: 0.9,
    pitch: 540,
    cost: 250,
    category: 'primary',
  },
  {
    id: 'verdict',
    name: 'VERDICT / SIX',
    class: 'Revolver',
    tag: 'PRECISION / IMPACT',
    role: 'Six precise shots with high sensor damage and a brief stagger. Reload before the rush reaches you.',
    damage: 55,
    rate: 2,
    mag: 6,
    reserve: 54,
    reload: 1.85,
    spread: 0.002,
    recoil: 0.045,
    range: 90,
    penetration: 0.45,
    weak: 3,
    stagger: 0.18,
    color: 0xbda991,
    length: 0.62,
    pitch: 120,
    cost: 180,
    category: 'secondary',
  },
  {
    id: 'tempest',
    name: 'TEMPEST / CLUSTER',
    class: 'Cluster launcher',
    tag: 'EXPLOSIVE / SCATTER',
    role: 'Each rocket splits into a wide fragmentation blast. Powerful crowd control with a smaller reserve.',
    damage: 135,
    rate: 0.7,
    mag: 2,
    reserve: 10,
    reload: 3,
    spread: 0.008,
    recoil: 0.07,
    range: 100,
    penetration: 0.7,
    weak: 1,
    explosive: 7.5,
    cluster: true,
    color: 0x9fba88,
    length: 1.3,
    pitch: 50,
    cost: 320,
    category: 'heavy',
  },
];
export const UPGRADES = [
  {
    id: 'loader',
    name: 'QUICKLOAD',
    description: 'Reload and vent 18% faster per rank.',
    cost: 100,
    max: 2,
  },
  {
    id: 'optics',
    name: 'SENSOR LINK',
    description: 'Sensor and exposed-core damage +15% per rank.',
    cost: 130,
    max: 2,
  },
  {
    id: 'plating',
    name: 'REACTIVE PLATE',
    description: 'Incoming damage reduced by 10% per rank.',
    cost: 150,
    max: 2,
  },
  {
    id: 'stride',
    name: 'SERVO TUNE',
    description: 'Movement speed +8% per rank.',
    cost: 100,
    max: 2,
  },
  {
    id: 'payload',
    name: 'WIDE PAYLOAD',
    description: 'Explosive radius +15% per rank.',
    cost: 120,
    max: 2,
  },
  {
    id: 'stabilizer',
    name: 'RECOIL DAMPER',
    description: 'Recoil reduced by 20% per rank.',
    cost: 90,
    max: 2,
  },
];
